osx_image: xcode7.3
language: objective-c

before_install:
    - git submodule update --init --recursive
    - brew update || brew update
    - brew outdated xctool || brew upgrade xctool
    - gem install cocoapods -v 0.39.0 --no-rdoc --no-ri --no-document --quiet

script:
    - xctool -workspace STM.xcworkspace -scheme STM build -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

branches:
  only:
    - master
