platform :ios, '9.0'
use_frameworks!

target 'STM' do
    pod 'DateTools', :git => 'https://github.com/MatthewYork/DateTools.git', :branch => 'swift', :commit => '8fe563153128b57d2ee5f4742e778d39effb4375'
    pod 'Gloss', :git => 'https://github.com/hkellaway/Gloss.git', :branch => 'swift_3.0'
    pod 'Hashids-Swift', :git => 'https://github.com/malczak/hashids', :branch => 'master'
    pod 'HPGrowingTextView'
    pod 'CryptoSwift'
    pod 'KILabel'
    pod 'Alamofire', '~> 4.0'
    pod 'Kingfisher'
    pod 'KMPlaceholderTextView'
    pod 'KZ', :git => 'https://github.com/k3zi/KZ.git', :branch => 'master'
    pod 'M13ProgressSuite'
    pod 'PRTween'
    pod 'PureLayout'
    pod 'Reusable', :git => 'https://github.com/phatblat/Reusable.git', :branch => 'ben/swift3'
    pod 'SAConfettiView', :git => 'https://github.com/gokhanakkurt/SAConfettiView.git', :branch => 'swift3'
    pod 'SecureNSUserDefaults'
    pod 'SpinKit'
    pod 'Socket.IO-Client-Swift'
    pod 'StreamingKit'
    pod 'Keynode'
    pod 'ALCameraViewController'
    pod 'DGElasticPullToRefresh'
    pod 'NYSegmentedControl'

    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TwitterKit'
    pod 'TwitterCore'
end
