platform :ios, '9.0'
use_frameworks!

target 'STM' do
    pod 'AeroGearHttp'
    pod 'DateTools'
    pod 'Gloss'
    pod 'Hashids-Swift'
    pod 'HPGrowingTextView'
    pod 'KILabel'
    pod 'Kingfisher'
    pod 'KMPlaceholderTextView'
    pod 'KZ'
    pod 'M13ProgressSuite'
    pod 'PRTween'
    pod 'PureLayout'
    pod 'RealmSwift'
    pod 'Reusable'
    pod 'SAConfettiView'
    pod 'SecureNSUserDefaults'
    pod 'SpinKit'
    pod 'Socket.IO-Client-Swift'
    pod 'StreamingKit'
    pod 'Keynode'

    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TwitterKit'
    pod 'TwitterCore'
end
