platform :ios, '9.0'
use_frameworks!

target 'STM' do
    pod 'DateTools', :git => 'https://github.com/MatthewYork/DateTools.git', :branch => 'swift'
    pod 'Gloss'
    pod 'Hashids-Swift', :git => 'https://github.com/malczak/hashids', :branch => 'master'
    pod 'HPGrowingTextView'
    pod 'CryptoSwift'
    pod 'KILabel'
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'KMPlaceholderTextView'
    pod 'KZ', :git => 'https://github.com/k3zi/KZ.git', :branch => 'master'
    pod 'M13ProgressSuite'
    pod 'PRTween'
    pod 'PureLayout'
    pod 'Reusable'
    pod 'SAConfettiView'
    pod 'SecureNSUserDefaults'
    pod 'SpinKit'
    pod 'Socket.IO-Client-Swift'
    pod 'StreamingKit'
    pod 'Keynode'
    pod 'ALCameraViewController'
    pod 'DGElasticPullToRefresh'
    pod 'NYSegmentedControl'

    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TwitterKit'
    pod 'TwitterCore'
end
