ENV["CRASHLYTICS_API_TOKEN"] = "0cff9cc7927135c3d29059393dd56ba7f01dc186"
ENV["CRASHLYTICS_BUILD_SECRET"] = "ea76c94efc96484ce0d6c8eb39079ad1423a836489e4ca6ddedb17806ba14b3d"
ENV["CRASHLYTICS_FRAMEWORK_PATH"] = "./Pods/Crashlytics/"

update_fastlane
default_platform :ios

def get_badge_version_string
  "#{get_version_number}-#{get_build_number}-blue"
end

def get_version_string
  "#{get_version_number}.#{get_build_number}"
end

def get_release_build_number
  number = "#{get_build_number}.1"
  number
end

lane :post_beta do |options|
  changelog = changelog_from_git_commits(pretty: '- (%ae) %s')

  increment_build_number
  new_version = get_version_string
  commit_version_bump(message: "bump version to: #{get_build_number}")

  badge(shield: "#{get_version_number}-#{get_build_number}-blue", shield_no_resize: false)
  match(type: 'adhoc', force_for_new_devices: true)
  gym(scheme: "STM", configuration: "Release", export_method: "ad-hoc", include_symbols: true)
  dsym_zip

  crashlytics(
      notes: changelog
  )

  if options[:testflight]
      match
      gym(scheme: "STM", configuration: "Release", include_symbols: true, include_bitcode: true)
      pilot(team_id: "117924857", skip_waiting_for_build_processing: true)
  end

  reset_git_repo(force: true)

  tag_name = "beta-#{new_version}"
  add_git_tag(tag: tag_name)
  push_to_git_remote()
  sh "git push origin --tags"
end

lane :post_store do
  ensure_git_branch(branch: 'master')
  increment_build_number
  new_version = get_version_string

  #match(type: "appstore")
  gym(scheme: "STM", configuration: "Release", export_method: "app-store", include_symbols: true, include_bitcode: true)
  deliver(force: true, skip_screenshots: true, skip_metadata: true)

  commit_version_bump(message: "bump version: #{get_build_number}")
  tag_name = "release-#{new_version}"
  add_git_tag(tag: tag_name)
  push_to_git_remote()
  sh "git push origin --tags"
end

lane :pre_dev do
  sigh(output_path: '/Library/Developer/XcodeServer/ProvisioningProfiles', development: true, skip_install: true)
end
